---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: discord-role-bot
      PROJECT_ID: discord-role-bot-380821
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/discord-role-bot/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/discord-role-bot/$IMAGE_NAME:$GIT_TAG
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/discord-role-bot/$IMAGE_NAME:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/discord-role-bot/$IMAGE_NAME:$GIT_TAG